alias darch 'docker inspect -f "{{.Architecture}}"'
alias dc    'docker compose'
alias dcb   'docker compose build'
alias dcr   'docker compose run'
alias di    'docker inspect'
alias dim   'docker images'
alias dn    'docker network'
alias dps   'docker ps'
alias drm   'docker rm -f'
alias drmi  'docker rmi'
alias dv    'docker volume'
alias dst   'docker stack'
alias ds    'docker service'
alias dsi   'docker service inspect --pretty'
alias dtty  'nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock'
